import { Typography } from 'antd';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-screen w">
          <div className="m-auto">
            <Typography.Title
              level={2}
              className="font-semibold text-success-color"
            >
              Next JS
            </Typography.Title>
          </div>
        </div>
      </main>
    </>
  );
}
